### ISSUE TITLE
Implement "on" data constraint

### ISSUE THREAD

**Issue by TristanDamron** [geoCML/tabor#11]
Consider the following Tabor file:

```
tabor: 0.2.0

layers:
    - name: x
      type: polygon
      owner: geocml
      schema: public
      fields:
          - name: id
             type: int
             pk: true

    - name: y
      type: point
      owner: geocml
      schema: public
      fields:
          - name: id
             type: int
             pk: true
     on: x       
```

The "on" keyword represents a data constraint. When we add this constraint to layer "y", we are saying that "every feature of y must be intersecting with some feature of x".

Supplemental reading: https://www.crunchydata.com/blog/spatial-constraints-with-postgis-part-2
