### ISSUE TITLE
Implement "near" data constraint

### ISSUE THREAD

**Issue by TristanDamron** [geoCML/tabor#19]
**Is your feature request related to a problem? Please describe.**
We need a data constraint that allows users to define a feature that is near another feature.

**Describe the solution you'd like**
The implementation should look something like this:

```yaml
tabor: 0.3.0

layers:
- name: feature_x
  schema: public
  owner: geocml
  geometry: point
  fields:
    - name: fid
       type: int
       pk: true

- name: feature_y
  schema: public
  owner: geocml
  geometry: point
  fields:
    - name: fid
       type: int
       pk: true

  constraints:
    - name: near
       layer: feature_x
       distance: 10
```

This Tabor file uses the "near" constraint which says that feature_y must be within 10 map units of feature_x
