### ISSUE TITLE
Implement "length" data constraint

### ISSUE THREAD

**Issue by TristanDamron** [geoCML/tabor#20]
**Is your feature request related to a problem? Please describe.**
For polyline features, users will need to define data constraints for the minimum and maximum length of a feature.

**Describe the solution you'd like**
The implementation should look something like this:

```yaml
tabor: 0.3.0

layers:
- name: feature_x
  schema: public
  owner: geocml
  geometry: polyline
  fields:
    - name: fid
       type: int
       pk: true

  constraints:
    - name: length
       minimum: 5

- name: feature_y
  schema: public
  owner: geocml
  geometry: polyline
  fields:
    - name: fid
       type: int
       pk: true

  constraints:
    - name: length
       maximum: 500
```

This Tabor file uses the "length" constraint to say that feature_x must have a minimum length of 5 map units, and that feature_y must have a maximum length of 500 map units. Both the "minimum" and "maximum" options can be used together on a single feature.

If the "length" constraint is used on non-polyline features, Tabor will throw an error.
