### ISSUE TITLE
"on" constraint doesn't work between points and lines

### ISSUE THREAD

**Issue by TristanDamron** [geoCML/tabor#23]
**Describe the bug**
Consider the following Tabor layers:

```yaml
- name: crossarms
  schema: public
  owner: geocml
  fields:
  - name: id
    type: int
    pk: true
  geometry: polyline


- name: insulators
  schema: public
  owner: geocml
  fields:
  - name: id
    type: int
    pk: true
  constraints:
  - name: 'on'
    layer: crossarms
  geometry: point
```

This should enforce a data constraint that says "insulators must be on crossarms", but unfortunately it doesn't seem to work.
