### ISSUE TITLE
Allow users to set spatial references for their layers

### ISSUE THREAD

**Issue by TristanDamron** [geoCML/tabor#35]
**Is your feature request related to a problem? Please describe.**
Tabor is currently limited in that it does not allow users to describe the desired spatial referencing system for their layers.

**Describe the solution you'd like**
A good solution might look something like this:

```yaml
tabor: 0.3.0
layers:
- name: some_poly
  schema: public
  owner: geocml
  srid: 4326
  fields:
  - name: fid
    type: int
    pk: true
  geometry: polygon
```

Users would add the ID of their desired spatial reference system per layer.
