### ISSUE TITLE
Support for domain values

### ISSUE THREAD

**Issue by TristanDamron** [geoCML/tabor#40]
**Is your feature request related to a problem? Please describe.**
Users will want to take advantage of defining their field domain values in .tabor files.

**Describe the solution you'd like**
```yaml
tabor: 4.0

domains:
- name: my_domain
   0: some_val_1
   1: some_val_2

layers:
- name: some_layer
  schema: public
  owner: geocml
  fields:
    - name: some_field
      type: my_domain 
```

This .tabor file creates a new domain called `my_domain` and a new layer which uses that domain for one of its fields.
